[package]
name = "wrap_tests"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.2.1", features = [ "unstable", ] }
#risc0-zkvm = { path = "../../../../risc0/risc0/zkvm/", features = [ "unstable", ] }
bls12_381 = { path = "../../.."}
